from django.urls import path

from .views import (
    device_detail,
    device_list_create,
    devices_summary,
    gateway_detail,
    gateway_list_create,
    gateways_summary,
    health,
    home_dashboard,
    index,
    overview,
    platform_login,
    platform_logout,
    platform_session,
    platform_user_create,
    platform_user_detail,
    platform_user_reset_password,
    platform_users,
    system_ports,
    system_status,
    telemetry_detail,
    telemetry_list_create,
    telemetry_summary,
    bigscreen_payload,
    video_inventory,
    video_runtime,
    video_status,
)

urlpatterns = [
    path('', index, name='index'),
    path('health/', health, name='health'),
    path('overview/', overview, name='overview'),
    path('video/status/', video_status, name='video-status'),
    path('video/runtime/', video_runtime, name='video-runtime'),
    path('video/inventory/', video_inventory, name='video-inventory'),
    path('video/bigscreen/', bigscreen_payload, name='video-bigscreen'),
    path('system/ports/', system_ports, name='system-ports'),
    path('system/status/', system_status, name='system-status'),
    path('home/dashboard/', home_dashboard, name='home-dashboard'),
    path('platform/session/', platform_session, name='platform-session'),
    path('platform/login/', platform_login, name='platform-login'),
    path('platform/logout/', platform_logout, name='platform-logout'),
    path('platform/users/', platform_users, name='platform-users'),
    path('platform/users/create/', platform_user_create, name='platform-user-create'),
    path('platform/users/<int:pk>/', platform_user_detail, name='platform-user-detail'),
    path('platform/users/<int:pk>/reset-password/', platform_user_reset_password, name='platform-user-reset-password'),
    path('gateways/', gateway_list_create, name='gateway-list-create'),
    path('gateways/summary/', gateways_summary, name='gateways-summary'),
    path('gateways/<int:pk>/', gateway_detail, name='gateway-detail'),
    path('devices/', device_list_create, name='device-list-create'),
    path('devices/summary/', devices_summary, name='devices-summary'),
    path('devices/<int:pk>/', device_detail, name='device-detail'),
    path('telemetry/', telemetry_list_create, name='telemetry-list-create'),
    path('telemetry/summary/', telemetry_summary, name='telemetry-summary'),
    path('telemetry/<int:pk>/', telemetry_detail, name='telemetry-detail'),
]
