# Generated by Django 5.2.12 on 2026-03-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('protocol', models.CharField(choices=[('modbus_rtu', 'Modbus RTU'), ('modbus_tcp', 'Modbus TCP'), ('mqtt', 'MQTT'), ('gb28181', 'GB28181'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.gateway')),
            ],
            options={
                'unique_together': {('gateway', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('collected_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.device')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.gateway')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
