# Generated by Django 5.2.12 on 2026-03-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('base_config', '基础配置'), ('collect_config', '数据采集配置'), ('protocol_config', '协议转换配置'), ('video_config', '视频接入配置'), ('cloud_config', '云平台推送配置')], max_length=64, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_by', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
